name: Publish levell jupyter docker image

# Controls when the workflow will run
on:
  # runs once every month
  schedule:
    - cron: "0 3 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push levell jupyter docker images to deployment server
    runs-on: ubuntu-latest
    
    steps:
      - 
        name: Check out the repo
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push levell jupyter hub docker
        uses: docker/build-push-action@v2
        with:
          push: true
          target: levell-jupyterhub-deploy
          tags: |
            ghcr.io/jimmylevell/jupyter/levell_jupyterhub:latest
      -
        name: Build and push levell jupyter docker
        uses: docker/build-push-action@v2
        with:
          push: true
          target: levell-jupyternotebook-deploy
          tags: |
            ghcr.io/jimmylevell/jupyter/levell_jupyternotebook:latest
      -
        name: Deploy to swarm
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: worker@levell.ch
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          deployment_mode: docker-swarm
          copy_stack_file: true
          pull_images_first: true
          deploy_path: /home/worker/levell/jupyter
          stack_file_name: docker-compose.prod.yml
          args: --with-registry-auth --prune jupyter
